ceramicnetwork/CIPs

CIPs/*INDEX/cip-index.csv, CIPs/CIP-2/CIP-2.md
Establish Discord as a platform for Ceramic community conversations
=> Ceramic Community Discord

CIPs/*INDEX/cip-index.csv, CIPs/CIP-3/CIP-3.md
Adds CIP for the Ceramic Ecosystem Alliance
=> Ceramic Ecosystem Alliance (CEA)

CIPs/CIP-59/CIP-59.md, CIPs/CIP-59/tables/doctypes.csv, CIPs/CIP-59/tables/subnets.csv, cip-template.md
PR for CIP https://github.com/ceramicnetwork/CIP/issues/59
=> cip: DocID encoding

CIPs/CIP-5/CIP-5.md
=> cip: Doctypes

CIPs/CIP-7/CIP-7.md
PR for CIP 8
Discussion: https://github.com/ceramicnetwork/CIP/issues/15
=> cip: CAIP-10 Link

CIPs/CIP-20/CIP-20.md
PR for CIP-20
Discussion: https://github.com/ceramicnetwork/CIP/issues/33
=> cip: 3ID Keychain

CIPs/CIP-21/CIP-21.md
PR for CIP-21
Discussion: https://github.com/ceramicnetwork/CIP/issues/44
=> cip: Crypto Accounts Definition

CIPs/CIP-19/CIP-19.md
PR for CIP-19: Basic Profile Definition
Discussions: https://github.com/ceramicnetwork/CIP/issues/32
=> cip: Basic Profile Definition

CIPs/CIP-71/CIP-71.md, CIPs/CIP-XX/CIP-XX.md
PR for CIP-71
All discussion to: https://github.com/ceramicnetwork/CIP/issues/72
=> cip: MultiQueries

CIPs/CIP-59/CIP-59.md, CIPs/CIP-59/tables/doctypes.csv, CIPs/CIP-59/tables/subnets.csv
Updates the spec to be aligned with the decided implementation.
=> chore: update docid cip

CIPs/CIP-23/CIP-23.md
PR for CIP-23
Discussion: https://github.com/ceramicnetwork/CIP/issues/55
=> cip: Also Known As Definition

CIPs/CIP-79/cip-79.md, CIPs/CIP-x/cip-x.md, INDEX.md
This PR introduces a CIP for the 3ID DID Method Specification
=> cip: 3ID DID Method Specification

CIPs/CIP-94/CIP-94.md, CIPs/CIP-XX/CIP-XX.md, INDEX.md
=> cip: NFT DID Method Specification

CIPs/CIP-11/CIP-11.md, CIPs/CIP-19/CIP-19.md, CIPs/CIP-20/CIP-20.md, CIPs/CIP-21/CIP-21.md, CIPs/CIP-23/CIP-23.md
Adds the StreamIDs for all of the schemas and definitions that we have deployed.
=> chore: Update deployed StreamIDs for IDX tiles

CIPs/CIP-101/CIP-101.md
According to proposed changes: https://github.com/ChainAgnostic/CAIPs/pull/59
=> Update to new caip10 format

CIPs/CIP-94/CIP-94.md
According to new chainId format.
=> Conform with new chainId format

INDEX.md
the titles within the CIPs themselves are already updated this way, just updating the index to match
=> Doc->Stream renames in CIP index

CIPs/cip-120.md, CIPs/cip-multiple-pubsub-topics.md, INDEX.md
[📚 Preview](https://github.com/ceramicnetwork/CIP/blob/cip/multiple-pubsub-topics/CIPs/cip-120.md)
=> CIP: Multiple pubsub topics

CIPs/CIP-59/tables/streamtypes.csv
=> Add ComposeDB stream types

README.md
=> Add editor Aaron Goldman

CIPs/cip-137.md
Based on a conversation with @AaronGoldman on how to best specify the sub-range of the subscription.
=> CIP-137 update range spec

CIPs/cip-146.md
Allow an Event to indicate an EventID that it was created after.
=> feat: after
